version: "2"

reviews:
  high_level_summary: true
  poem: true
  walkthrough: true
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "Draft"

chat:
  auto_reply: true

plugins:
  ast_grep:
    enabled: true
    patterns:
      - pattern: "console.log"
        message: "Ensure console.log is removed before merging to production."
        severity: "INFO"
